version: '3'
services:
  mirror-http:
    build: http
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-d6053178-cba1-41c6-b2ff-926dd94d457f/LinuxMirror/:/mnt/mirror/
    ports:
      - 8686:80
